# Generated by Django 3.2.6 on 2021-09-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='acceptance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='college',
            name='act',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='desirability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='domain',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='grad_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='college',
            name='influence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='overall_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='sat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='tuition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='undergrad_student_body',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
